vich_uploader:
    db_driver: orm

    mappings:
        article:
            uri_prefix: "/uploads/article"
            upload_destination: "%kernel.project_dir%/public/uploads/article"
            namer: vich_uploader.namer_uniqid
        categorie:
            uri_prefix: "/uploads/categorie"
            upload_destination: "%kernel.project_dir%/public/uploads/categorie"
            namer: vich_uploader.namer_uniqid
        video:
            uri_prefix: "/uploads/video"
            upload_destination: "%kernel.project_dir%/public/uploads/video"
            namer: vich_uploader.namer_uniqid

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
