#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# getUser:
#     path:     /uploads
#     defaults: { _controller: 'OurProject\UserEndpoint::get' }
#     methods:  [GET]

